version: 2

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install tox
        command: pip install --user tox
    - run:
        name: Run tox tests (for environments that match $CIRCLE_JOB)
        command: |
            export PATH="/home/circleci/.local/bin:$PATH"
            tox -e $(echo $(tox --listenvs | grep $CIRCLE_JOB) | sed -e 's/ /,/g')

jobs:
  py27:
    <<: *shared
    docker:
      - image: circleci/python:2.7

  py35:
    <<: *shared
    docker:
      - image: circleci/python:3.5

  py36:
    <<: *shared
    docker:
      - image: circleci/python:3.6

workflows:
  version: 2
  build:
    jobs:
      - py27
      - py35
      - py36
