version: 2

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: pip install --user tox
    - run: tox -e $(echo $(tox --listenvs | grep $TOX_PYTHON_ENV) | sed -e 's/ /,/g')

jobs:
  build_py27:
    <<: *shared
    environment:
      TOX_PYTHON_ENV: py27
    docker:
      - image: circleci/python:2.7

  build_py35:
    <<: *shared
    environment:
      TOX_PYTHON_ENV: py35
    docker:
      - image: circleci/python:3.5

  build_py36:
    <<: *shared
    environment:
      TOX_PYTHON_ENV: py36
    docker:
      - image: circleci/python:3.6
