version: 2.1

shared: &shared
  steps:
    - checkout
    - run:
        name: Install tox
        command: pip install --user tox
    - run:
        name: Run tox tests (for environments that match $CIRCLE_JOB)
        command: |
            # Filter for `tox` environments that match our Circle job names
            # (which correspond to Python versions of their Docker images)
            export MATCHING_ENVS="$(tox --listenvs | grep $CIRCLE_JOB)"

            # Comma-separate the tox environment names, and put 'em into the
            # env var where `tox` will see them
            export TOXENV="$(echo $MATCHING_ENVS | sed -e 's/ /,/g')"

            # Run tests
            tox
    - store_test_results:
        path: test-reports

jobs:
  py37:
    <<: *shared
    docker:
      - image: cimg/python:3.7

  py38:
    <<: *shared
    docker:
      - image: cimg/python:3.8

  py39:
    <<: *shared
    docker:
      - image: cimg/python:3.9

  py310:
    <<: *shared
    docker:
      - image: cimg/python:3.10

  py311:
    <<: *shared
    docker:
      - image: cimg/python:3.11

workflows:
  version: 2
  build:
    jobs:
      - py37
      - py38
      - py39
      - py310
      - py311
