version: 2.1

shared: &shared
  steps:
    - checkout
    - run:
        name: Install tox
        command: pip install --user tox
    - run:
        name: Run tox tests (for environments that match $CIRCLE_JOB)
        command: |
            # Run tests for the given Python version. The Circle job name
            # corresponds to the version of Python in use by that job.
            tox -e ${CIRCLE_JOB}
jobs:
  py37:
    <<: *shared
    docker:
      - image: cimg/python:3.7

  py38:
    <<: *shared
    docker:
      - image: cimg/python:3.8

  py39:
    <<: *shared
    docker:
      - image: cimg/python:3.9

  py310:
    <<: *shared
    docker:
      - image: cimg/python:3.10

workflows:
  version: 2
  build:
    jobs:
      - py37
      - py38
      - py39
      - py310
